NumPy - Numberical Python (Faster & allows several maths operations)

In [1]:
import numpy as np

List vs Numpy Array

In [2]:
from time import process_time

In [3]:
py_list = [i for i in range(100000)]

start = process_time()
py_list = [i + 5 for i in py_list]
end = process_time()

print('Time: ', end - start)

Time:  0.01620515600000072


In [5]:
np_array = np.array([i for i in range(100000)])

start = process_time()
np_array += 5
end = process_time()

print('Time: ', end - start)

Time:  0.001371622999999822


NumPy Arrays

In [10]:
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [12]:
# 2D Array
np_array = np.array([(1,2,3,4), (5,6,7,8)])
print(np_array)
np_array.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [14]:
np_array = np.array([(1,2,3,4), (5,6,7,8)], dtype = float)
print(np_array)
np_array.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

Initial placeholders in numpy arrays


In [15]:
# Creating a numpy array of 0s
x = np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# Creating a numpy array of 1s
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# Creating a numpy array with particular value
y = np.full((4,3),77)
print(y)

[[77 77 77]
 [77 77 77]
 [77 77 77]
 [77 77 77]]


In [22]:
# Creating identity matrix
i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# Creating a numpy array with random values
r = np.random.random((3,4))
print(r)

[[0.8123249  0.79699182 0.24197915 0.29054012]
 [0.18496784 0.45541198 0.01253609 0.32807293]
 [0.3999421  0.69939227 0.08082711 0.58603243]]


In [23]:
# Creating a numpy array with random integer values with range
r = np.random.randint(10, 100, (5,5))
print(r)

[[28 85 43 36 56]
 [94 13 19 49 36]
 [12 24 18 59 61]
 [16 87 14 12 68]
 [50 56 24 24 92]]


In [26]:
# Creating array of evenly spaced values
es = np.linspace(10, 20, 7)
print(es)

[10.         11.66666667 13.33333333 15.         16.66666667 18.33333333
 20.        ]


In [29]:
# Creating array of evenly spaced values but specifying the step
es = np.arange(5,30,2)
print(es)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [30]:
# Converting a list into numpy array 
list = [1,2,3,4,5]

np_list = np.asarray(list)
print(np_list)
type(np_list)

[1 2 3 4 5]


numpy.ndarray

Analysis of numpy array

In [31]:
r = np.random.randint(30, 300, (5,4))
print(r)

[[237 117  93 255]
 [ 57 268  87 187]
 [236 267 215 111]
 [201  77 237 237]
 [ 83  40  63 145]]


In [34]:
# Array Size
print(r.shape)

(5, 4)


In [35]:
# Array Dimension
print(r.ndim)

2


In [37]:
# Number of elements in array
print(r.size)

20


In [38]:
# Checking Data Type of elements
print(r.dtype)

int64


Mathematical Operation

In [40]:
# List 
l1 = [1,2,3,4,5]
l2 = [1,2,3,4,5]
print(l1 + l2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [42]:
# Numpy Array
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,2,3,4,5])
print(a1 + a2)

[ 2  4  6  8 10]


In [45]:
print(np.add(a1,a2))
print(np.subtract(a1,a2))
print(np.multiply(a1,a2))
print(np.divide(a1,a2))

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]


Array Manipulation

In [52]:
array = np.random.randint(1, 10, (2,3))
print(array)
print(array.shape)

[[5 2 7]
 [1 9 9]]
(2, 3)


In [54]:
# Transpose (Rows converted to columns and vice-versa)
trans = np.transpose(array)
print(trans)

[[5 1]
 [2 9]
 [7 9]]


In [55]:
# Reshaping a array
a = np.random.randint(0,10, (3,4))
print(a)
print(a.shape)

[[2 3 0 8]
 [1 2 6 7]
 [0 7 9 5]]
(3, 4)


In [56]:
b = a.reshape(4,3)
print(b)
print(b.shape)

[[2 3 0]
 [8 1 2]
 [6 7 0]
 [7 9 5]]
(4, 3)
